// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using adel_Mostafa_w4_0523035;

#nullable disable

namespace adel_Mostafa_w4_0523035.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241230113946_mg")]
    partial class mg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StratDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("t_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("p_id")
                        .HasColumnType("int");

                    b.Property<int?>("t_id")
                        .HasColumnType("int");

                    b.Property<int?>("tm_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("p_id");

                    b.HasIndex("tm_id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("t_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("teamMembers");
                });

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.Tasks", b =>
                {
                    b.HasOne("adel_Mostafa_w4_0523035.Models.Project", "project")
                        .WithMany("tasks")
                        .HasForeignKey("p_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("adel_Mostafa_w4_0523035.Models.TeamMember", "teammember")
                        .WithMany("tasks")
                        .HasForeignKey("tm_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("project");

                    b.Navigation("teammember");
                });

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.Project", b =>
                {
                    b.Navigation("tasks");
                });

            modelBuilder.Entity("adel_Mostafa_w4_0523035.Models.TeamMember", b =>
                {
                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
